// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV1ik07bG0bc0JuHMWwr9uaUYf-_grjHo',
    appId: '1:741229657315:web:6cf3ff08e1f05b5e6819d6',
    messagingSenderId: '741229657315',
    projectId: 'drive-clone-d79d9',
    authDomain: 'drive-clone-d79d9.firebaseapp.com',
    storageBucket: 'drive-clone-d79d9.appspot.com',
    measurementId: 'G-9EH5B4G6KD',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATnAbaZu0TaGb0nhlXkkaZl1QlinKrRIE',
    appId: '1:741229657315:ios:678c33f593134e516819d6',
    messagingSenderId: '741229657315',
    projectId: 'drive-clone-d79d9',
    storageBucket: 'drive-clone-d79d9.appspot.com',
    iosBundleId: 'com.example.gdriveClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCV1ik07bG0bc0JuHMWwr9uaUYf-_grjHo',
    appId: '1:741229657315:web:e53ff80766451f076819d6',
    messagingSenderId: '741229657315',
    projectId: 'drive-clone-d79d9',
    authDomain: 'drive-clone-d79d9.firebaseapp.com',
    storageBucket: 'drive-clone-d79d9.appspot.com',
    measurementId: 'G-VTWJP627EZ',
  );
}
